### ISSUE TITLE
Action Not Working

### ISSUE THREAD

**Issue by LiamJaco** [umutphp/github-action-dynamic-profile-page#5]
![image](https://github.com/user-attachments/assets/8ad7a200-c40a-4e2a-b290-818402e45427)

![Screenshot 2024-08-27 11 40 47 AM](https://github.com/user-attachments/assets/df413b3c-6f58-47e1-b01d-fb4f7c27d567)

It is saying that there is not Password for Https://GitHub.com

**Comment by umutphp** [comment]
Hi @LiamJaco ,

Many thanks for raising the issue. I will check and update you asap.

**Comment by LiamJaco** [comment]
Thank you

**Comment by umutphp** [comment]
Hi @LiamJaco ,

I have tested on my side, found a possible root cause and fixed. I have tried on my own repositories and saw that it worked.

Please check if you correctly follow the steps at the [usage](https://github.com/umutphp/github-action-dynamic-profile-page?tab=readme-ov-file#usage) section. 

Please also notice that you need to update the version of the action to "v4" as follows;

```
umutphp/github-action-dynamic-profile-page@v4
```

**Comment by LiamJaco** [comment]
Thank you so much!!

**Comment by LiamJaco** [comment]
It didn't work for me

![image](https://github.com/user-attachments/assets/32626298-27bb-4c10-baca-225783d216da)

**Comment by LiamJaco** [comment]
It worked, Thank you again!!

**Comment by LiamJaco** [comment]
I am getting this error now:

![image](https://github.com/user-attachments/assets/1bc80f8b-3680-4088-a343-a0e123dab8fc)

**Comment by umutphp** [comment]
Hi @LiamJaco ,

I think you have a newline character in the value of the API_TOKEN_GITHUB secret. Can you please check it?

**Comment by LiamJaco** [comment]
I deleted the repo

**Comment by LiamJaco** [comment]
I will reopen this issue if I get the same error
